Better error management for joedb_pack and joedb_inplace_pack

diff --git a/scripts/joedb_inplace_pack b/scripts/joedb_inplace_pack
--- a/scripts/joedb_inplace_pack
+++ b/scripts/joedb_inplace_pack
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 if [[ $# -eq 0 ]]; then
  echo "usage: $0 <file_name>+" >&2
  exit 1
@@ -11,9 +13,11 @@ for file_name in "$@"; do
  unpacked_name="$file_name".joedb_unpacked
 
  if [[ -e "$packed_name" ]]; then
-  echo "error: \"$packed_name\" already exists"
+  echo "error: \"$packed_name\" already exists" >&2
+  exit 1
  elif [[ -e "$unpacked_name" ]]; then
-  echo "error: \"$unpacked_name\" already exists"
+  echo "error: \"$unpacked_name\" already exists" >&2
+  exit 1
  else
   joedb_pack "$file_name" "$packed_name"
   mv "$file_name" "$unpacked_name"
